"""Regression test: every public symbol from app.foundation.models.entities remains importable
after refactoring the monolithic entities.py into a package."""

# Pre-computed from app/models/entities.py before splitting.
# Symbol census maintained as entities evolve (Aspect/KnowledgeItem dropped in advisor-loop PR1).

_EXPECTED_SYMBOLS = [
    "ActivityLedgerEntry",
    "AlphaSignal",
    "AlphacrafterJobRun",
    "AnalysisReport",
    "ApiKey",
    "AppSetting",
    "ASSET_TYPES",
    "Asset",
    "AttributionRun",
    "AuditLog",
    "BacktestResult",
    "Benchmark",
    "Category",
    "ChatMessage",
    "Composite",
    "CompositeMembership",
    "ConnectedAccount",
    "DataQualityEvent",
    "DiscoverCandidate",
    "DiscoverRun",
    "DkbAccount",
    "DkbDiagnosticRun",
    "DkbPosition",
    "DkbSyncLog",
    "DkbTransaction",
    "Embedding",
    "ExecutiveSummaryRecord",
    "Expense",
    "ExpenseRule",
    "FactorIcTracking",
    "FactorsLibrary",
    "FinAgentRun",
    "Fundamental",
    "Goal",
    "Holding",
    "Invoice",
    "JobRun",
    "LlmAdviceCard",
    "LlmAuditEvent",
    "LlmPortfolioDecision",
    "MacroIndicator",
    "McPathSample",
    "McRun",
    "MetaPolicySnapshot",
    "MultiHorizonVerdict",
    "NewsItem",
    "now_utc",
    "Nudge",
    "PaperHolding",
    "PaperPortfolio",
    "PaperSnapshot",
    "PaperTrade",
    "PasskeyCredential",
    "PasswordResetToken",
    "PerformanceLedgerEntry",
    "Portfolio",
    "PortfolioSnapshot",
    "PositionSnapshot",
    "PriceCache",
    "ProviderHealth",
    "QValue",
    "QuantExperiment",
    "QuantExperimentRun",
    "QuantFactorScore",
    "QuantMlModel",
    "QuantRlPolicy",
    "QuantRun",
    "QuantSavedScenario",
    "QuantSignal",
    "Recommendation",
    "RecommendationAttempt",
    "RecommendationDossier",
    "RecommendationOutcome",
    "RecommendationReview",
    "RegimeLabelHistory",
    "RegimeRecommendationWeight",
    "ScreenerRun",
    "ShadowPosition",
    "StockResearchReport",
    "StrategyGraveyardEntry",
    "Subscription",
    "TargetAllocation",
    "TaxLedgerEvent",
    "TaxLot",
    "TaxResidencyPeriod",
    "TraderBacktest",
    "TransactionLog",
    "User",
    "UserNewsRelevance",
    "uuid_pk",
    "VerificationAlert",
    "WatchlistItem",
]


def test_all_symbols_importable_from_entities_package():
    """Every expected name must be present as an attribute on the entities module."""
    import app.foundation.models.entities as entities

    missing = [name for name in _EXPECTED_SYMBOLS if not hasattr(entities, name)]
    assert not missing, f"Missing from app.foundation.models.entities: {missing}"


def test_all_symbols_importable_directly():
    """A single multi-name import statement proves every symbol resolves."""
    # fmt: off
    from app.foundation.models.entities import (  # noqa: F401
        ActivityLedgerEntry,
        AlphaSignal,
        AlphacrafterJobRun,
        AnalysisReport,
        ApiKey,
        AppSetting,
        ASSET_TYPES,
        Asset,
        AttributionRun,
        AuditLog,
        BacktestResult,
        Benchmark,
        Category,
        ChatMessage,
        Composite,
        CompositeMembership,
        ConnectedAccount,
        DataQualityEvent,
        DiscoverCandidate,
        DiscoverRun,
        DkbAccount,
        DkbDiagnosticRun,
        DkbPosition,
        DkbSyncLog,
        DkbTransaction,
        Embedding,
        ExecutiveSummaryRecord,
        Expense,
        ExpenseRule,
        FactorIcTracking,
        FactorsLibrary,
        FinAgentRun,
        Fundamental,
        Goal,
        Holding,
        Invoice,
        JobRun,
        LlmAdviceCard,
        LlmAuditEvent,
        LlmPortfolioDecision,
        MacroIndicator,
        McPathSample,
        McRun,
        MetaPolicySnapshot,
        MultiHorizonVerdict,
        NewsItem,
        now_utc,
        Nudge,
        PaperHolding,
        PaperPortfolio,
        PaperSnapshot,
        PaperTrade,
        PasskeyCredential,
        PasswordResetToken,
        PerformanceLedgerEntry,
        Portfolio,
        PortfolioSnapshot,
        PositionSnapshot,
        PriceCache,
        ProviderHealth,
        QValue,
        QuantExperiment,
        QuantExperimentRun,
        QuantFactorScore,
        QuantMlModel,
        QuantRlPolicy,
        QuantRun,
        QuantSavedScenario,
        QuantSignal,
        Recommendation,
        RecommendationAttempt,
        RecommendationDossier,
        RecommendationOutcome,
        RecommendationReview,
        RegimeLabelHistory,
        RegimeRecommendationWeight,
        ScreenerRun,
        ShadowPosition,
        StockResearchReport,
        StrategyGraveyardEntry,
        Subscription,
        TargetAllocation,
        TaxLedgerEvent,
        TaxLot,
        TaxResidencyPeriod,
        TraderBacktest,
        TransactionLog,
        User,
        UserNewsRelevance,
        uuid_pk,
        VerificationAlert,
        WatchlistItem,
    )
    # fmt: on


def test_legacy_models_module_import_still_works():
    """from app.foundation.models import entities must still resolve to the module."""
    from app.foundation.models import entities  # noqa: F401

    assert hasattr(entities, "User")
    assert hasattr(entities, "uuid_pk")
    assert hasattr(entities, "ASSET_TYPES")
