"""fk_indices_and_relationships

Revision ID: 2ce7981ac5c5
Revises: 0105_add_fk_indexes
Create Date: 2026-08-29 12:38:19.876931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2ce7981ac5c5'
down_revision: Union[str, Sequence[str], None] = '0105_add_fk_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _index_exists(inspector, table_name, index_name):
    """True if an index named ``index_name`` already exists on ``table_name``.

    Guards every index operation so this migration is idempotent and safe to
    re-run after a partial failure, and on databases whose schema was seeded by
    ``Base.metadata.create_all`` (model-level ``index=True`` columns such as
    ``quant_ml_models.kind`` already created indexes like ix_quant_ml_models_kind).
    """
    try:
        return index_name in {idx["name"] for idx in inspector.get_indexes(table_name)}
    except sa.exc.NoSuchTableError:
        return False


def safe_create_index(inspector, table_name, index_name, columns, unique=False):
    resolved = op.f(index_name)
    if not _index_exists(inspector, table_name, resolved):
        op.create_index(resolved, table_name, columns, unique=unique)


def safe_drop_index(inspector, index_name, table_name):
    resolved = op.f(index_name)
    if _index_exists(inspector, table_name, resolved):
        op.drop_index(resolved, table_name=table_name)



def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    # Whole-table drops are guarded: if a table was never created (or already
    # dropped) in a given environment, an unguarded op.drop_table would abort
    # the entire migration. The project convention is defensive has_table guards.
    if inspector.has_table('factor_loadings_daily'):
        safe_drop_index(inspector, 'ix_factor_loadings_daily_factor_ts', 'factor_loadings_daily')
        safe_drop_index(inspector, 'ix_factor_loadings_daily_symbol_factor_ts', 'factor_loadings_daily')
        op.drop_table('factor_loadings_daily')
    if inspector.has_table('recommendation_items'):
        safe_drop_index(inspector, 'ix_recommendation_items_report_id', 'recommendation_items')
        safe_drop_index(inspector, 'ix_recommendation_items_ticker', 'recommendation_items')
        op.drop_table('recommendation_items')
    if inspector.has_table('tax_year_summaries'):
        safe_drop_index(inspector, 'ix_tax_year_summaries_tax_year', 'tax_year_summaries')
        safe_drop_index(inspector, 'ix_tax_year_summaries_user_id', 'tax_year_summaries')
        op.drop_table('tax_year_summaries')
    if inspector.has_table('provider_health_history'):
        safe_drop_index(inspector, 'ix_provider_health_history_provider_ts', 'provider_health_history')
        op.drop_table('provider_health_history')
    if inspector.has_table('lean_backtest_runs'):
        safe_drop_index(inspector, 'ix_lean_backtest_runs_status', 'lean_backtest_runs')
        safe_drop_index(inspector, 'ix_lean_backtest_runs_user_id', 'lean_backtest_runs')
        op.drop_table('lean_backtest_runs')
    if inspector.has_table('regime_snapshots'):
        safe_drop_index(inspector, 'ix_regime_snapshots_label_ts', 'regime_snapshots')
        op.drop_table('regime_snapshots')
    if inspector.has_table('recommendation_reports'):
        safe_drop_index(inspector, 'ix_recommendation_reports_user_id', 'recommendation_reports')
        op.drop_table('recommendation_reports')
    if inspector.has_table('bar_prices'):
        if bind.dialect.name == "postgresql":
            # 0015's continuous aggregates depend on bar_prices; a fresh install
            # has them, so they must go first. 2ce7981ac5c7 recreates them.
            bind.execute(sa.text("DROP MATERIALIZED VIEW IF EXISTS bar_prices_monthly CASCADE"))
            bind.execute(sa.text("DROP MATERIALIZED VIEW IF EXISTS bar_prices_weekly CASCADE"))
        safe_drop_index(inspector, 'ix_bar_prices_symbol_ts', 'bar_prices')
        op.drop_table('bar_prices')

    # SQLite has no native ALTER COLUMN / DROP COLUMN support, so every
    # per-table column change is wrapped in op.batch_alter_table. On PostgreSQL
    # batch mode is a no-op wrapper that issues standard ALTER TABLE, so this is
    # safe and identical on both dialects.
    with op.batch_alter_table('activity_ledger_entries') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column('updated_at', existing_type=sa.DATETIME(), nullable=False)
    safe_drop_index(inspector, 'ix_activity_ledger_entries_connected_account_id', 'activity_ledger_entries')
    safe_drop_index(inspector, 'ix_advisor_graduation_state_strategy_id', 'advisor_graduation_state')
    safe_drop_index(inspector, 'ix_alphacrafter_job_runs_created_at', 'alphacrafter_job_runs')
    with op.batch_alter_table('analysis_reports') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=False)
    with op.batch_alter_table('assets') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column('updated_at', existing_type=sa.DATETIME(), nullable=False)
    safe_drop_index(inspector, 'ix_audit_logs_event_type_ts', 'audit_logs')
    with op.batch_alter_table('backfill_jobs') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=False)
    with op.batch_alter_table('competition_decisions') as batch_op:
        batch_op.alter_column('council_result_json', existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column('winner', existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column('errors', existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=False)
    safe_drop_index(inspector, 'ix_competition_decisions_portfolio_id', 'competition_decisions')
    safe_drop_index(inspector, 'ix_competition_decisions_run_id', 'competition_decisions')
    with op.batch_alter_table('competition_runs') as batch_op:
        batch_op.alter_column('name', existing_type=sa.VARCHAR(length=120), nullable=False)
        batch_op.alter_column('cadence_days', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('current_round', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('status', existing_type=sa.VARCHAR(length=24), nullable=False)
        batch_op.alter_column('state_json', existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column('started_at', existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column('updated_at', existing_type=sa.DATETIME(), nullable=False)
    safe_drop_index(inspector, 'ix_competition_runs_portfolio_a_id', 'competition_runs')
    safe_drop_index(inspector, 'ix_competition_runs_portfolio_b_id', 'competition_runs')
    safe_drop_index(inspector, 'ix_composite_membership_composite_id', 'composite_membership')
    safe_drop_index(inspector, 'ix_composite_membership_portfolio_id', 'composite_membership')
    with op.batch_alter_table('confidence_scores') as batch_op:
        batch_op.alter_column('factors_json', existing_type=sa.TEXT(), nullable=False)
    safe_create_index(inspector, 'confidence_scores', 'ix_confidence_scores_portfolio_id', ['portfolio_id'], unique=False)
    with op.batch_alter_table('connected_accounts') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column('updated_at', existing_type=sa.DATETIME(), nullable=False)
    with op.batch_alter_table('data_quality_events') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=False)
    safe_drop_index(inspector, 'ix_discover_candidates_dossier_id', 'discover_candidates')
    safe_drop_index(inspector, 'ix_discover_candidates_recommendation_id', 'discover_candidates')
    safe_drop_index(inspector, 'ix_discovery_config_parent_config_id', 'discovery_config')
    safe_drop_index(inspector, 'ix_discovery_config_review_champion_id', 'discovery_config_review')
    safe_drop_index(inspector, 'ix_discovery_config_review_promoted_id', 'discovery_config_review')
    with op.batch_alter_table('dkb_diagnostic_runs') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column('updated_at', existing_type=sa.DATETIME(), nullable=False)
    with op.batch_alter_table('dkb_sync_logs') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=False)
    safe_drop_index(inspector, 'ix_dkb_sync_logs_created_at', 'dkb_sync_logs')
    safe_drop_index(inspector, 'ix_dkb_transactions_category_id', 'dkb_transactions')
    safe_drop_index(inspector, 'ix_expense_rules_category_id', 'expense_rules')
    safe_drop_index(inspector, 'ix_expenses_category_id', 'expenses')
    with op.batch_alter_table('fx_rates') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=False)
    with op.batch_alter_table('llm_audit_events') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=False)
    # Backfill legacy NULL mandates. paper_portfolios enforces UNIQUE(user_id,
    # mandate) and the app only ever creates mandate='manual' (advisor later adds
    # 'A'/'B'), so a user may have at most one 'manual' portfolio. Users who
    # accumulated several NULL rows before the mandate column existed would
    # collide if every row were forced to 'manual'. A NULL row becomes 'manual'
    # ONLY when it is the first NULL row for that user AND the user has no
    # existing 'manual' portfolio; every other NULL row is re-labelled with a
    # distinct 'manual-legacy-N' mandate. No data is dropped and the unique
    # constraint stays satisfied, so the NOT NULL alter below is safe.
    # Implemented as a dialect-agnostic row loop (no UPDATE..FROM / window
    # functions) so it runs identically on PostgreSQL and SQLite.
    null_rows = bind.execute(sa.text(
        "SELECT id, user_id FROM paper_portfolios "
        "WHERE mandate IS NULL ORDER BY created_at ASC, id ASC"
    )).fetchall()
    existing_manual = {row[0] for row in bind.execute(sa.text(
        "SELECT DISTINCT user_id FROM paper_portfolios WHERE mandate = 'manual'"
    )).fetchall()}
    by_user: dict = {}
    for pid, uid in null_rows:
        by_user.setdefault(uid, []).append(pid)
    for uid, pids in by_user.items():
        if uid not in existing_manual:
            bind.execute(sa.text(
                "UPDATE paper_portfolios SET mandate = 'manual' WHERE id = :pid"
            ).bindparams(pid=pids[0]))
            for i, pid in enumerate(pids[1:], start=1):
                bind.execute(sa.text(
                    "UPDATE paper_portfolios SET mandate = :m WHERE id = :pid"
                ).bindparams(m="manual-legacy-%d" % i, pid=pid))
        else:
            for i, pid in enumerate(pids, start=1):
                bind.execute(sa.text(
                    "UPDATE paper_portfolios SET mandate = :m WHERE id = :pid"
                ).bindparams(m="manual-legacy-%d" % i, pid=pid))
    with op.batch_alter_table('paper_portfolios') as batch_op:
        batch_op.alter_column('mandate', existing_type=sa.VARCHAR(length=24), nullable=False)
    safe_create_index(inspector, 'paper_snapshots', 'ix_paper_snapshots_date', ['date'], unique=False)
    safe_create_index(inspector, 'paper_snapshots', 'ix_paper_snapshots_portfolio_date', ['portfolio_id', 'date'], unique=False)
    safe_drop_index(inspector, 'ix_paper_trades_holding_id', 'paper_trades')
    with op.batch_alter_table('provider_health') as batch_op:
        batch_op.alter_column('updated_at', existing_type=sa.DATETIME(), nullable=False)
    with op.batch_alter_table('quant_experiments') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column('updated_at', existing_type=sa.DATETIME(), nullable=False)
    safe_create_index(inspector, 'quant_ml_models', 'ix_quant_ml_models_kind', ['kind'], unique=False)
    safe_drop_index(inspector, 'ix_quant_runs_created_at', 'quant_runs')
    with op.batch_alter_table('recommendation_attempts') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=False)
    safe_drop_index(inspector, 'ix_recommendation_dossiers_attribution_run_id', 'recommendation_dossiers')
    safe_drop_index(inspector, 'ix_recommendation_dossiers_mc_run_id', 'recommendation_dossiers')
    with op.batch_alter_table('recommendation_reviews') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=False)
    with op.batch_alter_table('strategy_graveyard') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=False)
    safe_drop_index(inspector, 'ix_strategy_lessons_portfolio_id', 'strategy_lessons')
    safe_drop_index(inspector, 'ix_strategy_lessons_source_scorecard_id', 'strategy_lessons')
    safe_drop_index(inspector, 'ix_subscriptions_category_id', 'subscriptions')
    with op.batch_alter_table('tax_ledger_events') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=False)
    safe_drop_index(inspector, 'ix_tax_lots_jurisdiction_at_acquisition', 'tax_lots')
    with op.batch_alter_table('tax_lots') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column('updated_at', existing_type=sa.DATETIME(), nullable=False)
        batch_op.drop_column('jurisdiction_at_acquisition')
    safe_drop_index(inspector, 'ix_verification_alerts_portfolio_id', 'verification_alerts')
    safe_drop_index(inspector, 'ix_verification_alerts_user_acknowledged', 'verification_alerts')
    safe_create_index(inspector, 'verification_alerts', 'ix_verification_alerts_portfolio', ['portfolio_id'], unique=False)
    safe_create_index(inspector, 'verification_alerts', 'ix_verification_alerts_user_ack', ['user_id', 'acknowledged_at'], unique=False)
    safe_create_index(inspector, 'verification_alerts', 'ix_verification_alerts_user_id', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    # The upgrade drops the seven tables below (when present); the downgrade
    # must recreate them unconditionally to restore the 0105 schema. Guarding
    # these with has_table would silently skip recreation after a real upgrade.
    safe_drop_index(inspector, 'ix_verification_alerts_user_id', 'verification_alerts')
    safe_drop_index(inspector, 'ix_verification_alerts_user_ack', 'verification_alerts')
    safe_drop_index(inspector, 'ix_verification_alerts_portfolio', 'verification_alerts')
    safe_create_index(inspector, 'verification_alerts', 'ix_verification_alerts_user_acknowledged', ['user_id', 'acknowledged_at'], unique=False)
    safe_create_index(inspector, 'verification_alerts', 'ix_verification_alerts_portfolio_id', ['portfolio_id'], unique=False)
    op.add_column('tax_lots', sa.Column('jurisdiction_at_acquisition', sa.VARCHAR(length=2), server_default=sa.text("'DE'"), nullable=True))
    safe_create_index(inspector, 'tax_lots', 'ix_tax_lots_jurisdiction_at_acquisition', ['jurisdiction_at_acquisition'], unique=False)
    with op.batch_alter_table('tax_lots') as batch_op:
        batch_op.alter_column('updated_at', existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=True)
    with op.batch_alter_table('tax_ledger_events') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=True)
    safe_create_index(inspector, 'subscriptions', 'ix_subscriptions_category_id', ['category_id'], unique=False)
    safe_create_index(inspector, 'strategy_lessons', 'ix_strategy_lessons_source_scorecard_id', ['source_scorecard_id'], unique=False)
    safe_create_index(inspector, 'strategy_lessons', 'ix_strategy_lessons_portfolio_id', ['portfolio_id'], unique=False)
    with op.batch_alter_table('strategy_graveyard') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=True)
    with op.batch_alter_table('recommendation_reviews') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=True)
    safe_create_index(inspector, 'recommendation_dossiers', 'ix_recommendation_dossiers_mc_run_id', ['mc_run_id'], unique=False)
    safe_create_index(inspector, 'recommendation_dossiers', 'ix_recommendation_dossiers_attribution_run_id', ['attribution_run_id'], unique=False)
    with op.batch_alter_table('recommendation_attempts') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=True)
    safe_create_index(inspector, 'quant_runs', 'ix_quant_runs_created_at', ['created_at'], unique=False)
    safe_drop_index(inspector, 'ix_quant_ml_models_kind', 'quant_ml_models')
    with op.batch_alter_table('quant_experiments') as batch_op:
        batch_op.alter_column('updated_at', existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=True)
    with op.batch_alter_table('provider_health') as batch_op:
        batch_op.alter_column('updated_at', existing_type=sa.DATETIME(), nullable=True)
    safe_create_index(inspector, 'paper_trades', 'ix_paper_trades_holding_id', ['holding_id'], unique=False)
    safe_drop_index(inspector, 'ix_paper_snapshots_portfolio_date', 'paper_snapshots')
    safe_drop_index(inspector, 'ix_paper_snapshots_date', 'paper_snapshots')
    with op.batch_alter_table('paper_portfolios') as batch_op:
        batch_op.alter_column('mandate', existing_type=sa.VARCHAR(length=24), nullable=True)
    with op.batch_alter_table('llm_audit_events') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=True)
    with op.batch_alter_table('fx_rates') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=True)
    safe_create_index(inspector, 'expenses', 'ix_expenses_category_id', ['category_id'], unique=False)
    safe_create_index(inspector, 'expense_rules', 'ix_expense_rules_category_id', ['category_id'], unique=False)
    safe_create_index(inspector, 'dkb_transactions', 'ix_dkb_transactions_category_id', ['category_id'], unique=False)
    safe_create_index(inspector, 'dkb_sync_logs', 'ix_dkb_sync_logs_created_at', ['created_at'], unique=False)
    with op.batch_alter_table('dkb_sync_logs') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=True)
    with op.batch_alter_table('dkb_diagnostic_runs') as batch_op:
        batch_op.alter_column('updated_at', existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=True)
    safe_create_index(inspector, 'discovery_config_review', 'ix_discovery_config_review_promoted_id', ['promoted_id'], unique=False)
    safe_create_index(inspector, 'discovery_config_review', 'ix_discovery_config_review_champion_id', ['champion_id'], unique=False)
    safe_create_index(inspector, 'discovery_config', 'ix_discovery_config_parent_config_id', ['parent_config_id'], unique=False)
    safe_create_index(inspector, 'discover_candidates', 'ix_discover_candidates_recommendation_id', ['recommendation_id'], unique=False)
    safe_create_index(inspector, 'discover_candidates', 'ix_discover_candidates_dossier_id', ['dossier_id'], unique=False)
    with op.batch_alter_table('data_quality_events') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=True)
    with op.batch_alter_table('connected_accounts') as batch_op:
        batch_op.alter_column('updated_at', existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=True)
    safe_drop_index(inspector, 'ix_confidence_scores_portfolio_id', 'confidence_scores')
    with op.batch_alter_table('confidence_scores') as batch_op:
        batch_op.alter_column('factors_json', existing_type=sa.TEXT(), nullable=True)
    safe_create_index(inspector, 'composite_membership', 'ix_composite_membership_portfolio_id', ['portfolio_id'], unique=False)
    safe_create_index(inspector, 'composite_membership', 'ix_composite_membership_composite_id', ['composite_id'], unique=False)
    safe_create_index(inspector, 'competition_runs', 'ix_competition_runs_portfolio_b_id', ['portfolio_b_id'], unique=False)
    safe_create_index(inspector, 'competition_runs', 'ix_competition_runs_portfolio_a_id', ['portfolio_a_id'], unique=False)
    with op.batch_alter_table('competition_runs') as batch_op:
        batch_op.alter_column('updated_at', existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column('started_at', existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column('state_json', existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column('status', existing_type=sa.VARCHAR(length=24), nullable=True)
        batch_op.alter_column('current_round', existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column('cadence_days', existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column('name', existing_type=sa.VARCHAR(length=120), nullable=True)
    safe_create_index(inspector, 'competition_decisions', 'ix_competition_decisions_run_id', ['run_id'], unique=False)
    safe_create_index(inspector, 'competition_decisions', 'ix_competition_decisions_portfolio_id', ['portfolio_id'], unique=False)
    with op.batch_alter_table('competition_decisions') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column('errors', existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column('winner', existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column('council_result_json', existing_type=sa.TEXT(), nullable=True)
    with op.batch_alter_table('backfill_jobs') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=True)
    safe_create_index(inspector, 'audit_logs', 'ix_audit_logs_event_type_ts', ['event_type', 'created_at'], unique=False)
    with op.batch_alter_table('assets') as batch_op:
        batch_op.alter_column('updated_at', existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=True)
    with op.batch_alter_table('analysis_reports') as batch_op:
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=True)
    safe_create_index(inspector, 'alphacrafter_job_runs', 'ix_alphacrafter_job_runs_created_at', ['created_at'], unique=False)
    safe_create_index(inspector, 'advisor_graduation_state', 'ix_advisor_graduation_state_strategy_id', ['strategy_id'], unique=False)
    safe_create_index(inspector, 'activity_ledger_entries', 'ix_activity_ledger_entries_connected_account_id', ['connected_account_id'], unique=False)
    with op.batch_alter_table('activity_ledger_entries') as batch_op:
        batch_op.alter_column('updated_at', existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column('created_at', existing_type=sa.DATETIME(), nullable=True)
    op.create_table('bar_prices',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.FLOAT(), nullable=False),
    sa.Column('high', sa.FLOAT(), nullable=False),
    sa.Column('low', sa.FLOAT(), nullable=False),
    sa.Column('close', sa.FLOAT(), nullable=False),
    sa.Column('volume', sa.BIGINT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', 'ts', name=op.f('pk_bar_prices'))
    )
    safe_create_index(inspector, 'bar_prices', 'ix_bar_prices_symbol_ts', ['symbol', 'ts'], unique=False)
    op.create_table('recommendation_reports',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('portfolio_value', sa.FLOAT(), server_default=sa.text("'0.0'"), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'EUR'"), nullable=True),
    sa.Column('regime_label', sa.VARCHAR(length=32), server_default=sa.text("'unknown'"), nullable=True),
    sa.Column('regime_confidence', sa.FLOAT(), server_default=sa.text("'0.0'"), nullable=True),
    sa.Column('estimate', sa.BOOLEAN(), server_default=sa.text('(true)'), nullable=True),
    sa.Column('not_tax_advice', sa.BOOLEAN(), server_default=sa.text('(true)'), nullable=True),
    sa.Column('weights_json', sa.JSON(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('source_health_json', sa.JSON(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('raw_llm_output', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('validated_output', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('stripped_claims_json', sa.JSON(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendation_reports_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_reports'))
    )
    safe_create_index(inspector, 'recommendation_reports', 'ix_recommendation_reports_user_id', ['user_id'], unique=False)
    op.create_table('regime_snapshots',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.VARCHAR(length=80), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=40), nullable=False),
    sa.Column('payload_json', sa.TEXT(), server_default=sa.text("'{}'"), nullable=False),
    sa.PrimaryKeyConstraint('id', 'ts', name=op.f('pk_regime_snapshots'))
    )
    safe_create_index(inspector, 'regime_snapshots', 'ix_regime_snapshots_label_ts', ['label', 'ts'], unique=False)
    op.create_table('lean_backtest_runs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=160), nullable=False),
    sa.Column('status', sa.VARCHAR(length=24), server_default=sa.text("'created'"), nullable=False),
    sa.Column('command', sa.VARCHAR(length=80), server_default=sa.text("'backtest'"), nullable=False),
    sa.Column('project_dir', sa.TEXT(), nullable=True),
    sa.Column('template_json', sa.TEXT(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('result_json', sa.TEXT(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lean_backtest_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lean_backtest_runs'))
    )
    safe_create_index(inspector, 'lean_backtest_runs', 'ix_lean_backtest_runs_user_id', ['user_id'], unique=False)
    safe_create_index(inspector, 'lean_backtest_runs', 'ix_lean_backtest_runs_status', ['status'], unique=False)
    op.create_table('provider_health_history',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=40), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capability', sa.VARCHAR(length=80), nullable=False),
    sa.Column('ok', sa.BOOLEAN(), nullable=False),
    sa.Column('latency_ms', sa.FLOAT(), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'ts', name=op.f('pk_provider_health_history'))
    )
    safe_create_index(inspector, 'provider_health_history', 'ix_provider_health_history_provider_ts', ['provider', 'ts'], unique=False)
    op.create_table('tax_year_summaries',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('tax_year', sa.INTEGER(), nullable=False),
    sa.Column('payload_json', sa.TEXT(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tax_year_summaries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_year_summaries')),
    sa.UniqueConstraint('user_id', 'tax_year', name=op.f('uq_tax_year_summaries_user_year'))
    )
    safe_create_index(inspector, 'tax_year_summaries', 'ix_tax_year_summaries_user_id', ['user_id'], unique=False)
    safe_create_index(inspector, 'tax_year_summaries', 'ix_tax_year_summaries_tax_year', ['tax_year'], unique=False)
    op.create_table('recommendation_items',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('report_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('ticker', sa.VARCHAR(length=32), nullable=False),
    sa.Column('action', sa.VARCHAR(length=16), nullable=False),
    sa.Column('confidence', sa.VARCHAR(length=16), server_default=sa.text("'medium'"), nullable=True),
    sa.Column('timeframe', sa.VARCHAR(length=64), server_default=sa.text("'3-6 months'"), nullable=True),
    sa.Column('thesis', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('evidence_json', sa.JSON(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('risks_json', sa.JSON(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('data_quality', sa.VARCHAR(length=16), server_default=sa.text("'complete'"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['recommendation_reports.id'], name=op.f('fk_recommendation_items_report_id_recommendation_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_items'))
    )
    safe_create_index(inspector, 'recommendation_items', 'ix_recommendation_items_ticker', ['ticker'], unique=False)
    safe_create_index(inspector, 'recommendation_items', 'ix_recommendation_items_report_id', ['report_id'], unique=False)
    op.create_table('factor_loadings_daily',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=32), nullable=False),
    sa.Column('factor', sa.VARCHAR(length=80), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('loading', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'ts', name=op.f('pk_factor_loadings_daily'))
    )
    safe_create_index(inspector, 'factor_loadings_daily', 'ix_factor_loadings_daily_symbol_factor_ts', ['symbol', 'factor', 'ts'], unique=False)
    safe_create_index(inspector, 'factor_loadings_daily', 'ix_factor_loadings_daily_factor_ts', ['factor', 'ts'], unique=False)
    # ### end Alembic commands ###
