export interface GlossaryEntry { label: string; body: string }

export const glossary: Record<string, GlossaryEntry> = {
  // Wealth
  net_worth: { label: "Net worth", body: "Total mirrored cash and security value across connected accounts and manual holdings." },
  // Risk
  sharpe:    { label: "Sharpe ratio",    body: "Excess return per unit of total volatility. Higher is better; >1 is good, >2 is very good." },
  sortino:   { label: "Sortino ratio",   body: "Like Sharpe but only counts downside volatility." },
  calmar:    { label: "Calmar ratio",    body: "Annual return divided by max drawdown. Higher means stronger gain-to-pain." },
  treynor:   { label: "Treynor ratio",   body: "Return per unit of systematic (beta) risk." },
  beta:      { label: "Beta",            body: "Sensitivity to the benchmark. 1.0 moves like the market; >1 amplifies; <1 dampens." },
  alpha:     { label: "Alpha",           body: "Excess return relative to CAPM prediction. Positive = outperformed for its risk." },
  r_squared: { label: "R²",              body: "Share of portfolio variance explained by the benchmark (0–1)." },
  var_95:    { label: "VaR 95%",         body: "Daily loss expected to be exceeded only 5% of the time." },
  var_99:    { label: "VaR 99%",         body: "Daily loss expected to be exceeded only 1% of the time." },
  cvar_95:   { label: "CVaR 95%",        body: "Average loss on the worst 5% of days." },
  skew:      { label: "Skewness",        body: "Asymmetry. Negative = more big drops than big jumps." },
  kurtosis:  { label: "Excess kurtosis", body: "Fat-tail-ness. Positive = more extreme moves than a normal distribution." },
  max_drawdown:      { label: "Max drawdown",        body: "Worst peak-to-trough loss during the period." },
  drawdown_duration: { label: "Drawdown duration",   body: "How many trading days the portfolio stayed underwater." },
  info_ratio:        { label: "Information ratio",   body: "Active return divided by tracking error vs the benchmark." },
  annualised_return:      { label: "Annualised Return",      body: "The geometric average yearly return of the portfolio. It represents the constant annual rate that would produce the same cumulative return over the measurement period." },
  annualised_volatility:  { label: "Annualised Volatility",  body: "The standard deviation of the portfolio's annualised returns. A measure of risk and price fluctuation. Lower values indicate a more stable portfolio." },
  volatility:             { label: "Volatility",             body: "Standard deviation of returns, annualised. The primary measure of portfolio risk. Higher volatility implies greater price fluctuation and uncertainty." },
  downside_deviation:    { label: "Downside Deviation",    body: "A measure of downside risk that focuses on negative returns only. Unlike standard deviation, it penalises only losses, not gains." },
  win_rate:              { label: "Win Rate",              body: "The percentage of trades that generated a positive return. A win rate above 50% indicates more winning than losing trades, but must be considered alongside average win/loss size." },
  efficient_frontier:{ label: "Efficient frontier",  body: "Portfolios that offer the highest expected return for each volatility level." },
  min_volatility:    { label: "Minimum volatility",  body: "Optimised weights intended to minimise portfolio volatility." },
  max_sharpe:        { label: "Maximum Sharpe",       body: "Weights that maximise return per unit of estimated volatility." },
  inverse_volatility:{ label: "Inverse volatility",  body: "Weights assets inversely to their estimated volatility." },
  equal_weight:      { label: "Equal weight",        body: "Allocates the same weight to each eligible asset." },
  monte_carlo:       { label: "Monte Carlo",         body: "Simulated paths under explicit return and volatility assumptions." },
  factor_market:     { label: "Market factor",        body: "Exposure to broad market movement." },
  factor_size:       { label: "Size factor",          body: "Exposure to smaller-company return behaviour." },
  factor_value:      { label: "Value factor",         body: "Exposure to cheaper relative valuation styles." },
  factor_momentum:   { label: "Momentum factor",     body: "Exposure to assets with persistent recent relative performance." },
  tracking_error:    { label: "Tracking error",      body: "Volatility of returns relative to a benchmark." },
  turnover:          { label: "Turnover",            body: "Total portfolio weight changed by trading." },
  exposure_time:     { label: "Exposure time",       body: "Share of periods with market exposure." },
  hit_rate:          { label: "Hit rate",             body: "Share of active return periods that are profitable." },
  profit_factor:     { label: "Profit factor",        body: "Gross profits divided by gross losses." },
  cagr:              { label: "CAGR",                body: "Compound annual growth rate across the measured period." },
  // German tax (seeded; expanded in Phase 3)
  kest:                { label: "KESt",               body: "Kapitalertragsteuer — German 25% flat tax on investment income." },
  soli:                { label: "Solidaritätszuschlag", body: "5.5% surcharge on KESt, applied automatically." },
  vorabpauschale:      { label: "Vorabpauschale",     body: "Annual presumptive distribution on accumulating funds (§18 InvStG)." },
  teilfreistellung:    { label: "Teilfreistellung",   body: "Partial fund-class exemption: aktien 30%, misch 15%, immobilien 60%." },
  freistellungsauftrag:{ label: "Freistellungsauftrag", body: "Standard saver's allowance (1 000 € single / 2 000 € spouse)." },
  basiszins:            { label: "Basiszins",           body: "German base interest rate published by BMF each January, used to compute Vorabpauschale (§18 InvStG 2018)." },
  anlage_kap:           { label: "Anlage KAP",          body: "German tax return annex for investment income. The cockpit provides an estimate of what goes into each line." },
  fund_class_aktien:    { label: "Aktienfonds",         body: "Equity fund class receiving 30% Teilfreistellung (partial exemption)." },
  fund_class_misch:     { label: "Mischfonds",          body: "Mixed fund class receiving 15% Teilfreistellung." },
  fund_class_immobilien:{ label: "Immobilienfonds",     body: "Real estate fund class receiving 60% Teilfreistellung." },
  sparer_pauschbetrag:  { label: "Sparer-Pauschbetrag", body: "Standard lump-sum saver's allowance of 1 000 € (2 000 € for jointly assessed couples) on capital gains." },
  foreign_wht:          { label: "Foreign WHT",         body: "Withholding tax paid to a foreign tax authority. May be creditable against German KESt under a double-taxation treaty." },
  fifo:                 { label: "FIFO",                body: "First-in, first-out — the default method for calculating which specific shares were sold when computing gains." },
  // Monte Carlo (Phase 2)
  mc:                   { label: "Monte Carlo",         body: "Simulation method: many random paths sampled from a distribution, used to estimate option prices and risk metrics." },
  mlmc:                 { label: "Multilevel MC",       body: "MLMC: Giles hierarchical method using coarse and fine paths to reduce variance at lower cost than standard MC." },
  antithetic:           { label: "Antithetic sampling", body: "VR technique: pair each path with its negative to exploit correlation and reduce variance." },
  control_variate:      { label: "Control variate",     body: "VR technique: subtract a correlated cheaper-to-compute variable to reduce payoff variance." },
  importance_sampling:  { label: "Importance sampling", body: "VR technique: reweight paths by likelihood ratio to focus computational effort on rare events." },
  stratified:           { label: "Stratified sampling", body: "VR technique: divide the domain into strata and sample uniformly from each to ensure coverage." },
  pathwise_ipa:         { label: "Pathwise IPA",        body: "Greeks estimation: compute delta/gamma via infinitesimal perturbation analysis along the paths." },
  likelihood_ratio_greek: { label: "Likelihood ratio Greeks", body: "Greeks estimation for non-smooth payoffs: weight paths by d(log P)/dθ to estimate sensitivities." },
  heavy_tails:          { label: "Heavy tails",         body: "Distribution property: more extreme events than normal distribution. Captured by Student-t or NIG." },
  student_t:            { label: "Student-t",           body: "Heavy-tailed distribution with parameter ν (degrees of freedom); ν→∞ approaches normal." },
  nig:                  { label: "NIG",                 body: "Normal-Inverse-Gaussian: flexible heavy-tailed distribution used in quantitative finance." },
  variance_reduction:   { label: "Variance reduction",   body: "Techniques (antithetic, control variate, importance, stratified) to lower MC estimate variance without more paths." },
  // Attribution & Performance (Phase 3)
  brinson:              { label: "Brinson-Fachler",      body: "Attribution method that decomposes portfolio active return into allocation and selection effects." },
  allocation_effect:    { label: "Allocation effect",    body: "Brinson-Fachler component: contribution from over- or underweighting holdings vs the benchmark." },
  selection_effect:     { label: "Selection effect",     body: "Brinson-Fachler component: contribution from security performance relative to benchmark." },
  interaction_effect:   { label: "Interaction effect",   body: "Brinson-Fachler component: combined effect of weight and return differences from benchmark." },
  factor_attribution:   { label: "Factor attribution",   body: "Decomposition of returns by exposure to systematic factors (e.g., market, size, value, momentum)." },
  twr:                  { label: "TWR (Time-Weighted Return)", body: "Portfolio return independent of external cashflows; measures manager performance unbiased by fund size changes." },
  mwr:                  { label: "MWR (Money-Weighted Return)", body: "Portfolio return accounting for timing and size of cashflows (deposits/withdrawals); reflects investor experience." },
  composite:            { label: "Composite",            body: "User-defined grouping of multiple portfolios for consolidated performance reporting and benchmarking." },
  dispersion:           { label: "Dispersion",           body: "Standard deviation of returns across constituent portfolios within a composite; asset-weighted measure." },
  gips:                 { label: "GIPS",                 body: "Global Investment Performance Standards: CFA Institute framework for consistent, transparent performance reporting." },
  // FinAgent & LLM (Phase 6)
  rag:                  { label: "RAG",                  body: "Retrieval-Augmented Generation: LLM grounded in retrieved context from a knowledge base (e.g., financial corpus, wiki notes)." },
  embedding:            { label: "Embedding",            body: "Dense vector representation of text in a high-dimensional space, used for semantic similarity search in RAG." },
  priority_queue:       { label: "Priority Queue",       body: "Task scheduler that serves interactive queries first, batch work second, routine tasks last; prevents latency spikes." },
  cloud_fallback:       { label: "Cloud Fallback",       body: "Automatic fallback to Anthropic or OpenAI when local LLM is unavailable or degraded; routed for long-running batch work." },
  lora:                 { label: "LoRA",                 body: "Low-Rank Adaptation: efficient fine-tuning method that updates only a small number of additional parameters." },
  peft:                 { label: "PEFT",                 body: "Parameter-Efficient Fine-Tuning: family of methods (LoRA, QLoRA, etc.) that reduce memory and compute for model adaptation." },
  substitution_graph:   { label: "Substitution graph",   body: "Network of expense categories and cheaper alternatives, used to suggest budget optimisations." },
  financial_needs_hierarchy: { label: "Financial needs", body: "Framework ranking expense categories by priority: safety, income, growth, meaning; informs agent weighting." },
  // NL Box 3 (Phase 7)
  box3:                  { label: "Box 3",                body: "Dutch wealth tax (Box 3 der inkomstenbelasting) — annual tax on asset ownership at a fictitious return rate." },
  // Regime tab (WI-6)
  regime_bull:           { label: "Bull regime",          body: "The jump model's rising state: positive returns, small drawdown, calm volatility. Trend-following and momentum get more weight." },
  regime_bear:           { label: "Bear regime",          body: "The jump model's stressed state: deep drawdown and high volatility. Quality and liquidity get more weight, position sizes shrink and discovery pauses." },
  regime_sideways:       { label: "Sideways regime",      body: "The jump model's middle state, with no clear direction. Balanced (identity) factor weights: no tilt in any direction." },
  crisis_gate:           { label: "Crisis gate",          body: "A hard override that triggers when VIX exceeds the crisis threshold (default 30), credit spreads are wide, or the portfolio drawdown breaches a limit. When active, position limits tighten and cash floors rise regardless of the underlying regime label." },
  vix_indicator:         { label: "VIX",                  body: "CBOE Volatility Index — the market's 30-day implied volatility on S&P 500 options. Below 20 is calm, 20–30 is elevated, above 30 triggers the crisis gate. A rising VIX is the primary signal for defensive regime shifts." },
  yield_spread:          { label: "Yield Spread (10y–2y)", body: "US Treasury 10-year minus 2-year yield. A positive spread (normal curve) signals healthy growth expectations. A negative spread (inversion) has historically preceded recessions by 6–18 months and contributes to bear/crisis detection." },
  factor_affinity:       { label: "Factor affinity weights", body: "Multipliers (×) on each factor category's signal in Discover for the current jump-model state. Above 1.0 boosts the factor, below 1.0 damps it; in sideways every weight is 1.0." },
  factor_cat_momentum:   { label: "Momentum factor",      body: "Recent winners tend to keep winning for a while. ×1.2 in bull, ×0.5 in bear, where reversals are more frequent." },
  factor_cat_risk:       { label: "Risk factor",          body: "Short-term realised volatility, scored so calmer names rank higher. ×0.8 in bull, ×1.5 in bear." },
  factor_cat_trend:      { label: "Trend factor",         body: "The 50/200-day moving-average ratio. ×1.3 in bull, ×0.6 in bear, where trend signals are noisier." },
  factor_cat_liquidity:  { label: "Liquidity factor",     body: "Average trading volume. ×1.4 in bear, to favour positions that are easy to exit." },
  factor_cat_value:      { label: "Value factor",         body: "Earnings yield (E/P). ×0.9 in bull, ×0.7 in bear." },
  factor_cat_size:       { label: "Size factor",          body: "Log market capitalisation. ×1.1 in bull, ×0.6 in bear, where small caps tend to suffer more." },
  factor_cat_quality:    { label: "Quality factor",       body: "Return on equity. ×0.9 in bull, ×1.4 in bear, where strong balance sheets tend to hold up better." },
  vermogensrendementsheffing: { label: "Vermogensrendementsheffing", body: "Dutch asset tax: wealth is taxed at a prescribed notional return rate regardless of actual income." },
  heffingvrij_vermogen:  { label: "Heffingvrij vermogen", body: "Annual tax-free allowance in NL Box 3 (€57k in 2026); wealth below this threshold is exempt." },
  fictitious_return:     { label: "Fictitious return",    body: "Box 3: assumed notional return on wealth (1–6%) used for tax calculation, independent of actual investment returns." },
  tax_residency_period:  { label: "Tax residency",        body: "Date-bracketed residency classification for tax jurisdiction (DE, NL, etc.); used for dual-residency prorating." },
};

export function lookupGlossary(k: string): GlossaryEntry | undefined { return glossary[k]; }
